- name: install and run nginx
  hosts: web
  become: yes #root access
  tasks:
  - name: install nginx
    ansible.buildin.dnf:
     name: nginx
     state: latest
  - name: start nginx
    ansible.buildin.service:
      name: nginx
      state: started
      enabled: yes
