- name: variables
  hosts: localhost
  vars:
   Course: "aws-devops"
   Trainer: "siva"
   Duration: "150hrs"
  tasks:
  - name: print info
    vars:
     Course: "ansible"
     Trainer: "sivakumar"
     Duration: "15hrs"
    ansible.builtin.debug:
     msg: "hi, we are learning {{Course}} from Trainer {{Trainer}}, duration is {{Duration}}"