- name: variables from files
  hosts: web
  vars_files:
    vars.yaml
  tasks:
  - name: print info 
    ansible.builtin.debug:
     msg: "hi, we are learning {{Course}} from Trainer {{Trainer}}, duration is {{Duration}}"
