- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter ur username
    private: false
  - name: PASSWORD
    prompt: please enter ur password
    private: true
  tasks:
  - name: print info 
    ansible.builtin.debug:
     msg: "hi, username: {{USERNAME}}. Password:{{PASSWORD}}"