- name: data types
  hosts: localhost
  vars:
    Course: devops with aws #string
    Tools: #list
    - ansible
    - linux
    - git
    - jenkins
    Experience: #map or dictionary
      devops: 2
      aws: 2
      docker: 1
    RealProject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "course:{{Course}}, tools covered:{{Tools}}, experience with tools:{{Experience}}, is it realproject:{{RealProject}}"