- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{course | default('ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "hello. good mrng jai"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "hello. good mrng jai"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
   numbers: [1,2,2,23,3,3,4,4,4,5,5,6,6,6,7,8,8,9,9,9,9,7]
  tasks:
  - name: remove dupicate values
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"
    
- name: print min and max
  hosts: localhost
  vars:
   ages: [25,65,76,18,89,2]
  tasks:
  - name: print min and max age
    ansible.builtin.debug:
     msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

- name: convert dictionary or map or keyvalue pair into items/list
  hosts: localhost
  vars:
   my_dict:
   Course: ansible
   Trainer: siva
   Duration: 10hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
     msg: "before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
     msg: "after convert: {{ my_dict | dict2items }}"


