- name: demo on loops
  hosts: localhost
  become: yes
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{item}}"
    loop:
    - linux
    - git
    - maven
    - jenkins
    - docker
    - kubernetes
    - terraform
    - ansible
    - aws 
